name: Update Deployment Badge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Update Badge with Current Date
      run: |
        # Get current date
        CURRENT_DATE=$(date +%Y%m%d)
        
        # Update README.md
        sed -i "s/Last%20Updated-[0-9]\{8\}/Last%20Updated-$CURRENT_DATE/g" README.md
        sed -i "s/Last%20Updated-[0-9]\{8\}/Last%20Updated-$CURRENT_DATE/g" README_zh.md
        
        # Check if there are changes
        if git diff --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        # Commit changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md README_zh.md
        git commit -m "Update deployment badge date"
        git push